//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FlowTrace.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDI_ICON_TREE_ROOT              502
#define IDI_ICON_TREE_APP               503
#define IDI_ICON_TREE_THREAD            504
#define IDI_ICON_TREE_PAIRED            505
#define IDI_ICON_TREE_ENTER             506
#define IDI_ICON_TREE_EXIT              507
#define IDI_ICON_LIST_ENTER             508
#define IDI_ICON_LIST_EXIT              509
#define IDI_ICON_LIST_TRACE_SEL         513
#define IDC_STATIC_INFO                 517
#define IDC_PROGRESS                    518
#define IDD_PROGRESS                    519
#define IDD_SETTINGS                    520
#define IDD_DETAILES                    521
#define IDI_ICON_NODE_COLAPSED          524
#define IDI_ICON_NODE_EXPANDED          525
#define IDI_ICON_NODE_CHECKED           526
#define IDI_ICON_NODE_UNCHECKE          527
#define IDI_ICON_EMPTY1                 528
#define IDI_ICON_BOOKMARK               528
#define IDD_SNAPSHOTS                   529
#define IDI_ICON_SYNC                   529
#define IDR_FONT1                       530
#define IDB_TTF_BMP                     531
#define IDB_SYNC                        535
#define IDB_FUNC_IN_ECLIPSE             536
#define IDD_INFO                        536
#define IDB_SYNC2                       537
#define IDB_CALL_IN_ECLIPSE             537
#define IDD_MODULES                     538
#define IDC_NN                          1000
#define IDC_APP                         1001
#define IDC_FONT_NAME                   1002
#define IDC_TID                         1003
#define IDC_BTN_FONT                    1004
#define IDC_PID2                        1004
#define IDC_THREAD_NN                   1004
#define IDC_TIME                        1005
#define IDC_EDIT_PORT                   1006
#define IDC_PID                         1006
#define IDC_CALL_ADDR                   1007
#define IDC_CHECK1                      1008
#define IDC_CALL_ADDR2                  1008
#define IDC_CHECK_SHOW_APP_TIME         1008
#define IDC_CHILD_COUNT                 1008
#define IDC_CHECK_PREFERED_MODULE       1008
#define IDC_CHECK_USE_PC_TIME           1009
#define IDC_CALL_ADDR3                  1009
#define IDC_FN_CALL_LINE                1009
#define IDC_CALL_LINE                   1020
#define IDC_CHECK_USE_PC_TIME2          1021
#define IDC_CHECK_COMPACT_VIEW          1022
#define IDC_LIST_SNAPSHOTS              1023
#define IDC_CHECK_RESOLVE_ADDR          1023
#define IDC_FUNC_NAME                   1024
#define IDC_CHECK_COMPACT_VIEW3         1024
#define IDC_CHECK_FULL_SRC_PATH         1024
#define IDC_BUTTON_ADD                  1025
#define IDC_CHECK_UDATE_STACK_VIEW      1025
#define IDC_CHECK_SHOW_APP_IP           1026
#define IDC_CHECK_ECLIPSE_ON_WIN        1026
#define IDC_NN2                         1027
#define IDC_CHECK_SHOW_APP_IP2          1027
#define IDC_CHECK_SHOW_ELAPSED_TIME     1027
#define IDC_LINE_NN                     1028
#define IDC_LIST2                       1029
#define IDC_EDIT_COMMENT                1040
#define IDC_COMBO1                      1041
#define IDC_COMBO_FONTS                 1042
#define IDC_COMBO_FONT_SIZE             1043
#define IDC_CHECK_FONT_WEIGHT           1044
#define IDC_BUTTON1                     1045
#define IDC_BUTTON_EDIT                 1046
#define IDC_BUTTON_DEL                  1047
#define IDC_BUTTON_RESET                1200
#define IDC_EDIT_LINUX_HOME             1201
#define IDC_EDIT2                       1202
#define IDC_EDIT_MAP_ON_WIN             1202
#define IDC_EDIT1                       1202
#define IDC_EIDT_INFO                   1202
#define IDC_EDIT_PREFERED_MODULE        1202
#define IDC_EDIT_ECLIPSE_ON_WIN         1203
#define IDC_STATIC_MODULES              1203
#define IDC_STATIC_MODUL_LST            1203
#define IDC_EDIT_EXTERNAL_COMMAND       1204
#define IDC_EDIT_ANDROID_STUDIO         1205
#define IDC_EDIT_ANDOID_PROJECT         1206
#define IDC_EDIT_ANDROID_PROJECT        1206
#define ID_VIEW_SHOW_HIDE_STACK         32774
#define ID_VIEW_SHOW_HIDE_TREE          32775
#define ID_VIEW_STARTRECORDIG           32776
#define ID_VIEW_PAUSERECORDING          32777
#define ID_SEARCH_COMBO                 32778
#define ID_SEARCH_CLEAR                 32779
#define ID_SEARCH_REFRESH               32780
#define ID_SEARCH_NEXT                  32781
#define ID_SEARCH_PREV                  32782
#define ID_SEARCH_LAST                  32783
#define ID_SEARCH_FIRST                 32784
#define ID_SEARCH_MATCH_CASE            32785
#define ID_SEARCH_MATCH_WHOLE_WORD      32786
#define ID_FILE_EXPORT                  32787
#define ID_FILE_IMPORT                  32788
#define ID_VIEW_DETAILES                32789
#define ID_VIEW_SETTINGS                32790
#define ID_VIEW_CLEARLOG                32791
#define ID_SHOW_CALL_IN_FUNCTION        32792
#define ID_SHOW_FUNCTION                32793
#define ID_SYNC_VIEWES                  32794
#define ID_EDIT_SELECTALL               32795
#define ID_EDIT_FIND32798               32798
#define ID_VIEW_NODE_DATA               32799
#define ID_EDIT_FINDNEXT                32801
#define ID_EDIT_FINNDPREVIOUS           32802
#define ID_EDIT_FINDLAST                32803
#define ID_EDIT_FINDFIRST               32804
#define ID_TREE_PREV_SIBLING            32805
#define ID_TREE_NEXT_SIBLING            32806
#define ID_VIEW_SHOW                    32810
#define ID_VIEW_SHOW_HIDE_FLOW_TRACES   32811
#define ID_TREE_EXPAND_ALL              32812
#define ID_TREE_COLLAPSE_ALL            32813
#define ID_TREE_FIRST_SIBLING           32814
#define ID_TREE_COPY_CALL_PATH          32815
#define ID_VIEW_SYNCRONISEVIEWS         32816
#define ID_SEARCH_REFRESH_ON_EMTER      32817
#define ID_EDIT_BOOKMARKS               32818
#define ID_TREE_LAST_SIBLING            32819
#define ID_BOOKMARKS_NEXTBOOKMARK       32820
#define ID_BOOKMARKS_PREVIOUSBOOKMARK   32821
#define ID_BOOKMARKS_CLEARBOOKMARKS     32822
#define ID_BOOKMARKS_TOGGLE             32823
#define ID_VIEW_TAKESNAPSHOT            32826
#define ID_VIEW_STARTNEWSNAPSHOT        32828
#define ID_EDIT_COPY_ALL                32829
#define ID_EDIT_COPY_TRACES             32830
#define ID_CALL_STACK                   32831
#define ID_VIEW_RUN_EXTERNAL_CMD        32832
#define ID_VIEW_MODULES                 32833
#define ID_VIEW_RESETLOG                32834

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        540
#define _APS_NEXT_COMMAND_VALUE         32835
#define _APS_NEXT_CONTROL_VALUE         1204
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
